name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: arduino/setup-arduino-cli@v1
    - name: Install Arduino CLI

    - uses: actions/checkout@v3
    - name: build
      run: g++ -o main src/main.cpp
           ./main
