name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Compile Arduino Sketches
      uses: arduino/compile-sketches@v1.1.0

    - uses: actions/checkout@v3
      name: build
      run: g++ -o main src/main.cpp
           ./main
