name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: gcc -o main src/main.cpp
           ./main
