name: Google Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install google test
        run: |
          cd Test/GoogleTest/
          git clone https://github.com/google/googletest.git

      - name: Test
        run: |
          cmake

